FROM node:11.8.0-alpine

# Create app directory
RUN mkdir -p /usr/src/app/client
WORKDIR /usr/src/app/client

# install dependencies
COPY package*.json ./
RUN npm cache verify && npm install
# RUN npm i -g serve

# copy app source to image _after_ npm install so that
# application code changes don’t bust the docker cache of 
# npm install step
COPY . .

# set application PORT and expose docker PORT, 80 is what Elastic Beanstalk expects
EXPOSE 3000

CMD ["npm", "start"]